### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by alex2awesome** [janosh/tensorboard-reducer#13] opened 2021-11-05 06:35 UTC
Hey, I think the version in `pip` is different from what I briefly leafed through on Github... anyway, when I try to import and follow your example, I get the following import error:

```
from glob import glob
from tensorboard_reducer import load_tb_events, reduce_events, write_csv, write_tb_events
```

```Traceback (most recent call last):

  File "/Users/alex/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-d171cc7f8b6d>", line 2, in <module>
    from tensorboard_reducer import load_tb_events, reduce_events, write_csv, write_tb_events

  File "/Users/alex/opt/anaconda3/lib/python3.7/site-packages/tensorboard_reducer/__init__.py", line 1, in <module>
    from .io import load_tb_events, write_csv, write_tb_events

  File "<fstring>", line 1
    (overwrite=)
              ^
SyntaxError: invalid syntax```

**Comment by janosh** [comment] 2021-11-05 06:42
It looks like you're using Python < 3.8? The readme indicates you need 3.8 or later which added [self-documenting f-strings](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging). If you're bound to an earlier Python, the easiest fix might be to install `tensorboard-reducer` into a virtual env.

**Comment by p-enel** [comment] 2021-11-05 20:21
I had the same issue and the python version was indeed the cause.

**Comment by janosh** [comment] 2021-11-08 20:26
@p-enel Thanks for confirming! Closing as documented version requirement then but feel free to ping back if there's another issue here.

**Closed by janosh** 2021-11-08 20:26 UTC
Labels: question
